---
version: "1.0"
services:
  ssh-gost:
    image: subinghong/ubuntu-ssh:gost_
    container_name: ssh_gost
    environment:
      - TAILSCALE_KEY=${TAILSCALE_KEY}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME}
      - GOST_PASSWORD=${GOST_PASSWORD}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - VSC_PASSWORD=${VSC_PASSWORD}
      - VSC_ENABLE=${VSC_ENABLE}
    volumes:
      - /mydata:/mydata
    ports:
      - 80:80
    restart: unless-stopped
