---
version: "1.0"
services:
  ssh-gost:
    image: "${IMAGE_PATH}"
    container_name: ssh-gost
    environment:
      - TAILSCALE_KEY=${TAILSCALE_KEY}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME}
      - GOST_PASSWORD=${GOST_PASSWORD}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - VSC_PASSWORD=${VSC_PASSWORD}
      - VSC_ENABLE=${VSC_ENABLE}
    volumes:
      - vsc:/mydata
    ports:
      - 80:80
    restart: unless-stopped
volumes:
  vsc:
    driver_opts:
      class: standard
      size: 5Gi
