---
version: "2.1"
services:
  ssh-gost:
    image: subinghong/ubuntu-ssh:gost_
    container_name: ssh_gost
    environment:
      - NONE_VAR=NONE
    volumes:
      - /mydata:/mydata
    ports:
      - 80:80
    restart: unless-stopped
